os:
  - Visual Studio 2017

configuration:
  - Release

platform:
  - Win32
  
install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - vcpkg integrate install
  - vcpkg install freetype  
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
  - cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build:
  project: fontbm.sln
  
after_build:
 - 7z a fontbm.zip "./Release/*" "-x!unit_tests.exe"

artifacts:
  - path: fontbm.zip
    name: fontbm

deploy:
  provider: GitHub
  description: 'fontbm windows binaries'
  auth_token:
    secure: nXiCCnu0iLt3SzV9/DYgOnI5UHWDogpqrUNJq7OsbLkSVGKyEO2b3XrbAFjn2LER
  artifact: fontbm
  on:
    appveyor_repo_tag: true
